version: '3.8'

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=generosity
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network

  frontend:
    container_name: frontend
    build: ./frontend
    depends_on:
      - backend
    environment:
      - HOST=0.0.0.0
      - NUXT_PUBLIC_BACKEND_URL=http://localhost:8081
      - NUXT_PRIVATE_BACKEND_URL=http://backend:8081
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network

  db:
    container_name: database
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=generosity
      - POSTGRES_DB=generosity
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  host:
    driver: host
